language: node_js

services:
  - docker

node_js:
  - '10'

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache: npm

before_deploy:
  - git config --local user.name "Manuel-777"
  - git config --local user.email "manuel.etchegaray7@gmail.com"

jobs:
  include:
    - stage: Linux build
      os: linux
      dist: xenial
      sudo: required
      script: |
         docker run --rm -ti \
         --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
         --env ELECTRON_CACHE="/root/.cache/electron" \
         --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
         -v ${PWD}:/project \
         -v ${PWD##*/}-node-modules:/project/node_modules \
         -v ~/.cache/electron:/root/.cache/electron \
         -v ~/.cache/electron-builder:/root/.cache/electron-builder \
         electronuserland/builder:wine \
         /bin/bash -c "yarn && yarn dist"
         npm run dist
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        api_key:
          secure: Uc4t5CwRHkBhgLWN5AXEMMfuRUnhfehf5aYY/owh5jzKLxOfKt5ysWY3+95NAzaIoXST1noJfCQehpnOhMA+g9rcq+xzlcJ2EgVAfTnXyPhrGyU5K7uKgpeeRnLfqmZfm0VhVoxurCK761lFRMgTJR4RtMH4+5XFUGHm1aEd6jWa3clTH5oLOMPCW1I4jyMHO7YPUHL4quxYem/b+a+H7AtkCgHHxXYn6WjISrmRwbE65UCJt7Gud9lxQmp14nVTmWi9iyL0M9ClOlwA2MmT19B8Keb5MLqwIqTMABBm4uNmV6JE19uuOgZfRS/7fvQZOrGXwIEz+vZeu/VTWSk2QvBo1TJ6uPL7IP4znB+HqFUVWClbNg/xHD89Mpd/KPVvOMEEU3U3Ms1oV0SvsfUkmn50X80fAXhREM8+MHdkYE+N+cSd8AeMof1yLrIks879wm4IOuywjY4vAizq99phDajCBHS0287HeC3+Vx4u/E5NApyzKPwbWH/fDR1BrEGpr2xMPwgY29mVzs2Cali0MZYuWjJA2Y3AwuhyUzUu27C062bwE6zVELzf/myKcskIkebrqDqwYjs0sKEVsBnTD48GPdSYSrEg3utAQ5+w0qbJM/+2f0MAjY2y4e7j57eiltVP/dUzIl/C6bl1fqz6PQFMbEyyBVCqiO84sxStjjc=
        file: dist/*
        on:
          tags: true
          repo: Manuel-777/MTG-Arena-Tool
    - stage: Mac build
      os: osx
      script:
        - npm run dist
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        api_key:
          secure: Uc4t5CwRHkBhgLWN5AXEMMfuRUnhfehf5aYY/owh5jzKLxOfKt5ysWY3+95NAzaIoXST1noJfCQehpnOhMA+g9rcq+xzlcJ2EgVAfTnXyPhrGyU5K7uKgpeeRnLfqmZfm0VhVoxurCK761lFRMgTJR4RtMH4+5XFUGHm1aEd6jWa3clTH5oLOMPCW1I4jyMHO7YPUHL4quxYem/b+a+H7AtkCgHHxXYn6WjISrmRwbE65UCJt7Gud9lxQmp14nVTmWi9iyL0M9ClOlwA2MmT19B8Keb5MLqwIqTMABBm4uNmV6JE19uuOgZfRS/7fvQZOrGXwIEz+vZeu/VTWSk2QvBo1TJ6uPL7IP4znB+HqFUVWClbNg/xHD89Mpd/KPVvOMEEU3U3Ms1oV0SvsfUkmn50X80fAXhREM8+MHdkYE+N+cSd8AeMof1yLrIks879wm4IOuywjY4vAizq99phDajCBHS0287HeC3+Vx4u/E5NApyzKPwbWH/fDR1BrEGpr2xMPwgY29mVzs2Cali0MZYuWjJA2Y3AwuhyUzUu27C062bwE6zVELzf/myKcskIkebrqDqwYjs0sKEVsBnTD48GPdSYSrEg3utAQ5+w0qbJM/+2f0MAjY2y4e7j57eiltVP/dUzIl/C6bl1fqz6PQFMbEyyBVCqiO84sxStjjc=
        file: dist/*
        on:
          tags: true
          repo: Manuel-777/MTG-Arena-Tool